version: '3.3'
services:
  laravel-app:
    build: .
    ports:
      - "8181:80"
      #      para não matar minha mudança ao dar docker compose down
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network
  mysql-app:
    image: mysql:8.0.27
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: "ps_semsa20212_db"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
