<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AvaliacaoReprovarRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth()->check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'motivo_rep' => 'required|string|max:500'
        ];
    }

    public function messages()
    {
        return [
            'motivo_rep.required' => 'É necessário preencher o campo com o motivo para reprovação.',
            'motivo_rep.max' => 'O campo de reprovação só aceitar 500 caracteres.',
        ]; // TODO: Change the autogenerated stub
    }
}
