<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CarrosselRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'file_img' => 'mimes:jpg,png,jpeg|required',
            'url_link' => 'max:200',
        ];
    }

    public function messages()
    {
        return [
            'file_img.mimes' => 'Esse tipo de arquivo não é aceito, somente arquivos do tipo jpg, png, jpeg',
            'file_img.required' => 'A imagem é obrigatória.',
            'url_link.max' => 'O tamanho máximo de caracteres do link é de 200.'
        ]; // TODO: Change the autogenerated stub
    }
}
