<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RecursoAdminRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth()->check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'pessoa_id' => 'required|exists:pessoa,id',
            'motivo_reav' => 'required|string|max:16777214',
        ];
    }

    public function messages()
    {
        return [
            'pessoa_id.required' => 'Recurso selecionado inválido.',
            'pessoa_id.exists' => 'Recurso selecionado inválido.',
            'motivo_reav.required' => 'Motivo para recursar deve ser preenchido.',
            'motivo_reav.max' => 'O máximo de caracteres permitidos é de 500.',
        ]; // TODO: Change the autogenerated stub
    }
}
